### ISSUE TITLE
Include dependencies SOPS

### ISSUE THREAD

**Issue by Nico-DB** [taimos/secretsmanager-versioning#11]
Currently i have to install SOPS manually for my CodeBuild. Since I am using the newest version of SOPS i don't know if this matches to the code of secretsmanager-versioning. It would be nice, if the program includes SOPS.

**Comment by hoegertn** [comment]
This would add around 100MB of binaries for the different platforms. Not sure this is a great idea.

It is also not clear if this is permitted by the license SOPS uses.
